spring.application.name=notification-service

server.port=8087

# ==========================================
# ORACLE DATABASE
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ==========================================
# JWT
# ==========================================

jwt.secret=FarmXPSecretKeyForJWTAuthentication2026VerySecureKey

# ==========================================
# EUREKA
# ==========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.compatibility-verifier.enabled=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true



# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ==========================================
# SWAGGER
# ==========================================

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
